# Default values for integrationTests.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  namespace: default
  docker:
    #repository: "" #Docker-hub default
    pullPolicy: IfNotPresent
  service:
    zookeeper:
      name: zookeeper-k8s
      port: 2181 
      image: confluentinc/cp-zookeeper:7.3.1
      enabled: true
    broker:
      name: server-k8s
      port: 9092
      image: confluentinc/cp-server:7.3.1
      enabled: true
    extractor:
      name: yfinance-extractor
      image: yfinance-extractor-001:latest
      port: 5050
      enabled: true
    application:
      name: yfinance-stock-price-alarm-processor
      image: yfinance-stock-price-alarm-processor-001:latest
      port: 4040
      partitions: 1
      replicationFactor: 1
      createKafkaTopics:
        - "yfinance-raw-input"
        - "yfinance-after-dedup-storage-table"
        - "yfinance-after-dedup-stream"
      enabled: true